(() => {
'use strict';
const $ = id => document.getElementById(id);
const canvas = $('mirror'), ctx = canvas.getContext('2d', {alpha:false}), video = $('camera');
const sheet = new Image(); sheet.src = 'spritesheet.webp';
const TAU = Math.PI * 2, clamp = (v,a,b) => Math.max(a,Math.min(b,v));
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
const palettes = [{h:157,a:'#9df7d5',name:'LUMOS',caption:'Egy apró mozdulat. Egy kis csoda.'},{h:266,a:'#cab0ff',name:'KOZMOSZ',caption:'Egy egész univerzum az ujjaid között.'},{h:32,a:'#ffd098',name:'FŐNIX',caption:'Ébreszd fel a benned rejlő tüzet.'}];
let world=0,w=0,h=0,dpr=1,t=0,last=0,scale=1,targetScale=1,rotation=0,targetRotation=0,energy=0,waveUntil=0,lastBurst=0;
let cx=0,cy=0,dx=0,dy=0,tx=0,ty=0,points=[],sparks=[],rings=[],pointerActive=false;
let stream=null,landmarker=null,ready=false,starting=false,lastVideo=-1,lastDetect=0,pinched=false;
const touches=new Map();
const stars=Array.from({length:180},()=>({x:Math.random(),y:Math.random(),z:Math.random(),phase:Math.random()*TAU}));
const particles=Array.from({length:700},(_,i)=>({angle:Math.random()*TAU,r:.6+Math.random()*.58,z:Math.random(),phase:i*.73}));
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);cx=w*(w<721?.5:.55);cy=h*(w<721?.55:.49);}
function color(alpha=1,offset=0){return `hsla(${palettes[world].h+offset},75%,72%,${alpha})`;}
function glow(x,y,r,alpha,offset=0){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color(alpha,offset));g.addColorStop(1,color(0,offset));ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
function burst(x=cx+dx,y=cy+dy){const now=performance.now();if(now-lastBurst<180)return;lastBurst=now;energy=1;waveUntil=now+1400;rings.push({x,y,r:5,life:1});for(let i=0;i<100;i++){const a=Math.random()*TAU,v=1+Math.random()*7;sparks.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:1,size:Math.random()*2+1});}if(sparks.length>550)sparks.splice(0,sparks.length-550);}
function processPoints(list){points=list.slice(0,2);$('hand-count').textContent=`${points.length} / 2`;$('track-fill').style.width=`${points.length*50}%`;if(!points.length){pinched=false;targetScale=1;return;}tx=points.reduce((s,p)=>s+p.x,0)/points.length-cx;ty=points.reduce((s,p)=>s+p.y,0)/points.length-cy;tx=clamp(tx,-w*.19,w*.19);ty=clamp(ty,-h*.17,h*.17);if(points.length===2){const ordered=[...points].sort((a,b)=>a.x-b.x);const [a,b]=ordered;targetScale=clamp(Math.hypot(a.x-b.x,a.y-b.y)/(Math.min(w,h)*.48),.65,1.65);targetRotation=Math.atan2(b.y-a.y,b.x-a.x);}else{targetScale=1;targetRotation=tx/w;}const pinch=points.some(p=>p.pinch);if(pinch&&!pinched)burst(points[0].x,points[0].y);pinched=pinch;}
function paint(now){requestAnimationFrame(paint);if(document.hidden)return;const dt=Math.min((now-last)/16.667,2)||1;last=now;t+=dt*(reduced?.002:.009);dx+=(tx-dx)*.065;dy+=(ty-dy)*.065;scale+=(targetScale-scale)*.055;rotation+=(targetRotation-rotation)*.06;energy*=.975;
ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#061112';ctx.fillRect(0,0,w,h);const x=cx+dx,y=cy+dy;const radius=Math.min(w*(w<721?.36:.215),h*.34)*scale;
glow(x,y,radius*2.5,.11);glow(w*.88,h*.85,w*.45,.025,40);
for(const s of stars){const sx=(s.x*w+dx*s.z*.25+w)%w,sy=(s.y*h+dy*s.z*.25+h)%h;ctx.fillStyle=color(.12+s.z*.45*(.7+Math.sin(t+s.phase)*.3),s.z>.8?45:0);ctx.beginPath();ctx.arc(sx,sy,.4+s.z,0,TAU);ctx.fill();}
ctx.save();ctx.translate(x,y);ctx.rotate(rotation);
// Fine, tilted orbital paths give the portal volume.
for(let j=0;j<6;j++){ctx.save();ctx.rotate(j*.47+t*.04*(j%2?1:-1));ctx.strokeStyle=color(j===0?.35:.12,j%2?30:0);ctx.lineWidth=j===0?1.2:.6;ctx.beginPath();ctx.ellipse(0,0,radius*(1.05+j*.085),radius*(.72+j*.046),0,0,TAU);ctx.stroke();ctx.restore();}
ctx.save();ctx.rotate(-t*.12);ctx.setLineDash([2,13]);ctx.strokeStyle=color(.35,35);ctx.beginPath();ctx.arc(0,0,radius*1.27,0,TAU);ctx.stroke();ctx.setLineDash([]);for(let i=0;i<12;i++){const a=i*TAU/12;ctx.save();ctx.rotate(a);ctx.translate(radius*1.27,0);ctx.rotate(Math.PI/4);ctx.strokeStyle=color(.55,35);ctx.strokeRect(-3,-3,6,6);ctx.restore();}ctx.restore();
ctx.globalCompositeOperation='lighter';
for(const p of particles){const a=p.angle+t*(.14+p.z*.17);const ripple=Math.sin(a*5+t+p.phase)*.025;const rr=radius*(p.r+ripple+energy*.13);const px=Math.cos(a)*rr,py=Math.sin(a)*rr*.89;const opacity=.15+p.z*.6;ctx.fillStyle=color(opacity,p.z>.73?40:0);ctx.beginPath();ctx.arc(px,py,(.35+p.z*1.35)*(1+energy),0,TAU);ctx.fill();if(p.z>.94){ctx.strokeStyle=color(.24,30);ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(px-Math.sin(a)*9,py+Math.cos(a)*9);ctx.stroke();}}
ctx.globalCompositeOperation='source-over';glow(0,0,radius*.9,.10);ctx.restore();
// Original Dobby sprite sheet: eight columns, nine animation rows.
if(sheet.complete&&sheet.naturalWidth){const waving=now<waveUntil,row=waving?3:0,frame=Math.floor(now/(waving?150:240))%(waving?4:6);const sh=sheet.naturalHeight/9,sw=sheet.naturalWidth/8;const size=Math.min(radius*1.09,300);const bob=reduced?0:Math.sin(t*1.6)*6;ctx.save();ctx.shadowColor=color(.6);ctx.shadowBlur=25;ctx.imageSmoothingEnabled=false;ctx.drawImage(sheet,frame*sw,row*sh,sw,sh,x-size/2,y-size*.53+bob,size,size*sh/sw);ctx.restore();}
// Floating motes gather around both fingertips.
for(const p of points){glow(p.x,p.y,60,.17);ctx.strokeStyle=color(.7);ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,p.pinch?12:22,0,TAU);ctx.stroke();ctx.beginPath();ctx.arc(p.x,p.y,3,0,TAU);ctx.fillStyle='#e9fff2';ctx.fill();if(!reduced&&Math.random()>.4)sparks.push({x:p.x,y:p.y,vx:(Math.random()-.5)*2,vy:-Math.random()*2,life:.55,size:1.3});}
if(points.length===2){ctx.strokeStyle=color(.4);ctx.setLineDash([3,8]);ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);ctx.lineTo(points[1].x,points[1].y);ctx.stroke();ctx.setLineDash([]);}
ctx.globalCompositeOperation='lighter';sparks=sparks.filter(p=>p.life>0);for(const p of sparks){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.018*dt;p.life-=.014*dt;ctx.fillStyle=color(Math.max(0,p.life),35);ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,TAU);ctx.fill();}rings=rings.filter(r=>r.life>0);for(const r of rings){r.r+=7*dt;r.life-=.018*dt;ctx.strokeStyle=color(Math.max(0,r.life)*.6);ctx.lineWidth=2;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,TAU);ctx.stroke();}ctx.globalCompositeOperation='source-over';
if(ready&&now-lastDetect>65&&video.readyState>=2&&video.currentTime!==lastVideo){lastDetect=now;lastVideo=video.currentTime;try{const result=landmarker.detectForVideo(video,now);if(!pointerActive){processPoints(result.landmarks.map(hand=>{const palm=Math.hypot(hand[0].x-hand[9].x,hand[0].y-hand[9].y);return{x:(1-hand[8].x)*w,y:hand[8].y*h,pinch:Math.hypot(hand[8].x-hand[4].x,hand[8].y-hand[4].y)<palm*.38};}));}}catch(error){stopCamera();setStatus('A kézkövetés megszakadt. Próbáld újra a kamerát.');}}
}
function setStatus(message){$('status').textContent=message;}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointerActive=true;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});processPoints([...touches.values()]);burst(e.clientX,e.clientY);});
canvas.addEventListener('pointermove',e=>{if(touches.has(e.pointerId)){touches.set(e.pointerId,{x:e.clientX,y:e.clientY});processPoints([...touches.values()]);}else if(!ready){tx=(e.clientX-cx)*.32;ty=(e.clientY-cy)*.28;}});
function endPointer(e){touches.delete(e.pointerId);pointerActive=touches.size>0;processPoints([...touches.values()]);}
canvas.addEventListener('pointerup',endPointer);canvas.addEventListener('pointercancel',endPointer);canvas.addEventListener('lostpointercapture',endPointer);
canvas.addEventListener('wheel',e=>{e.preventDefault();targetScale=clamp(targetScale-e.deltaY*.001,.65,1.65);},{passive:false});
$('burst').onclick=()=>burst();document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['BUTTON','INPUT','A'].includes(document.activeElement.tagName)){e.preventDefault();burst();}});
document.querySelectorAll('.world').forEach(button=>button.addEventListener('click',()=>{world=Number(button.dataset.world);document.documentElement.style.setProperty('--accent',palettes[world].a);$('spell-name').textContent=palettes[world].name;$('spell-caption').textContent=palettes[world].caption;document.querySelectorAll('.world').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});burst();}));
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setStatus('A teljes képernyő ebben a böngészőben nem érhető el.');}};
function stopCamera(){ready=false;stream?.getTracks().forEach(track=>track.stop());stream=null;video.srcObject=null;landmarker?.close();landmarker=null;$('preview').hidden=true;$('camera-label').textContent='Kamera bekapcsolása';$('input-label').textContent='EGÉR / ÉRINTÉS';processPoints([]);}
$('camera-toggle').onclick=async()=>{if(ready){stopCamera();setStatus('Kamera kikapcsolva. Folytasd egérrel vagy érintéssel.');return;}if(starting)return;if(!isSecureContext||!navigator.mediaDevices?.getUserMedia){setStatus('A kamerához HTTPS vagy localhost szükséges. Egérrel máris varázsolhatsz.');return;}starting=true;$('camera-toggle').disabled=true;$('camera-label').textContent='Varázslat betöltése…';setStatus('Engedélyezd a kamerát, majd mutasd az egyik vagy mindkét kezed.');try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:'user',width:{ideal:640},height:{ideal:480}}});video.srcObject=stream;await video.play();const {FilesetResolver,HandLandmarker}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.21/+esm');const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.21/wasm');const options={baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.55,minTrackingConfidence:.55};try{landmarker=await HandLandmarker.createFromOptions(vision,options);}catch{options.baseOptions.delegate='CPU';landmarker=await HandLandmarker.createFromOptions(vision,options);}ready=true;lastVideo=-1;$('preview').hidden=false;$('camera-label').textContent='Kamera kikapcsolása';$('input-label').textContent='KÉZVEZÉRLÉS AKTÍV';setStatus('Mozgasd a kezed • Csippents a szikrákhoz • Két kézzel tágítsd a portált');}catch(error){stopCamera();setStatus(error.name==='NotAllowedError'?'A kamera nincs engedélyezve. Egérrel és érintéssel is működik.':error.name==='NotFoundError'?'Nem található kamera. Egérrel és érintéssel is varázsolhatsz.':'A kamera vagy a kézmodell nem tölthető be. Ellenőrizd a kapcsolatot, és próbáld újra.');}finally{starting=false;$('camera-toggle').disabled=false;}};
sheet.onerror=()=>setStatus('Dobby képe nem tölthető be. Ellenőrizd a spritesheet.webp fájlt.');
window.addEventListener('resize',resize);window.addEventListener('pagehide',stopCamera);resize();requestAnimationFrame(paint);
})();
